name: json_serializable_ex
description: json_serializable_ex
version: 0.0.3
publish_to: none
# homepage: https://www.example.com
# https://www.raywenderlich.com/22180993-flutter-code-generation-getting-started#toc-anchor-016

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  build: any
  recase : any
  source_gen: any
  analyzer: 3.2.0
  foundation:
    git:
      url: https://github.com/pshonkaaa/package.foundation.dart.git
  json_ex:
    git:
      url: https://github.com/pshonkaaa/package.json_ex.dart.git
  json_annotation_ex:
    git:
      url: https://github.com/pshonkaaa/package.json_annotation_ex.dart.git

dev_dependencies:
  build_runner: any
  build_test: any
  test: ^1.0.0
